### ISSUE TITLE
Respect NSFW Tag

### ISSUE THREAD

**Issue by johjeff** [coolstar/Capella#15]
I noticed pictures that had the NSFW hiding them in the web client are showing automatically in Capella. The app should respect the NSFW tag to avoid potentially embarrassing situations. You should be able to click to un-hide and click again to re-hide the image. I think that is a pretty important feature.

Otherwise, very nice client, and much more convenient that keeping Mastodon open in a browser.

Thank you for your work on this project.

**Comment by astra-midnight** [comment]
Will be in the next release.
