### ISSUE TITLE
Add Twitter support

### ISSUE THREAD

**Issue by Niquarl** [coolstar/Capella#16]
I've been looking for a simple app that would allow to have both Twitter and Mastodon streams and haven't found a single one. Would this app be instered in implementing this ?

**Comment by rodneyrod** [comment]
Agreed. There's not any clients on desktop that I'm aware of that do Twitter and Mastodon in the same client, unless you have Windows 10.

**Comment by astra-midnight** [comment]
I'm not sure this is within the scope of the project at the moment. That may change in the future though.

**Comment by coolstar** [comment]
I have a very similar Arcturus project (which is what Capella is based off) which is a Twitter client. I haven't released the other project but may consider open sourcing that too

That being said... http://apps-of-a-feather.com/

Looks like twitter clients are dying :(

**Comment by rodneyrod** [comment]
@coolstar This doesn't appear to be affecting the Corebird dev team, maybe there's a way they know to get around this issue. If I were you I would contact them and see what they have to say.

**Comment by rodneyrod** [comment]
@coolstar Did you end up talking with the Corebird team?
